#!/bin/bash

g++ -Wall -g -W -Werror -Wno-unused-parameter -Wno-unused-variable \
    -I ./src/include \
    src/*.cpp \
    src/**/*.cpp \
    src/glad.c \
    -o bin/output \
    -lglfw -ldl -lGL || exit 1
